# Generated by Django 5.0.6 on 2024-05-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_main', '0002_rename_phone_contactform_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='number',
            field=models.CharField(max_length=15),
        ),
    ]
