# Generated by Django 5.0.6 on 2024-05-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_main', '0003_alter_contactform_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='date',
            field=models.DateField(max_length=15),
        ),
    ]
